/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wwtbam;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Class representing a new game of Who Wants To Be A Millionaire
 * @author Devin Grant-Miles
 */
public class WWTBAMView extends javax.swing.JFrame 
{
    /**
     * Creates new form WWTBAMView
     */
    public WWTBAMView() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textDisplayPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDisplayLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        gameButtonPanel = new javax.swing.JPanel();
        aButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        fifty50Button = new javax.swing.JButton();
        askAudButton = new javax.swing.JButton();
        phoneButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Who Wants To Be A Millionaire");

        textDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textDisplayLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        textDisplayLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        textDisplayLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        textDisplayLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jScrollPane1.setViewportView(textDisplayLabel);

        javax.swing.GroupLayout textDisplayPanelLayout = new javax.swing.GroupLayout(textDisplayPanel);
        textDisplayPanel.setLayout(textDisplayPanelLayout);
        textDisplayPanelLayout.setHorizontalGroup(
            textDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        textDisplayPanelLayout.setVerticalGroup(
            textDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );

        buttonPanel.setLayout(new java.awt.CardLayout());

        aButton.setText("A");

        bButton.setText("B");

        cButton.setText("C");

        dButton.setText("D");

        fifty50Button.setText("50/50");

        askAudButton.setText("Ask the Audience");

        phoneButton.setText("Phone a Friend");

        startButton.setText("Start");

        quitButton.setText("Quit");

        helpButton.setText("Help");

        nameTextField.setText("Please input your name...");

        javax.swing.GroupLayout gameButtonPanelLayout = new javax.swing.GroupLayout(gameButtonPanel);
        gameButtonPanel.setLayout(gameButtonPanelLayout);
        gameButtonPanelLayout.setHorizontalGroup(
            gameButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(gameButtonPanelLayout.createSequentialGroup()
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addComponent(helpButton)
                .addGap(271, 271, 271)
                .addComponent(quitButton))
            .addGroup(gameButtonPanelLayout.createSequentialGroup()
                .addGroup(gameButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aButton)
                    .addComponent(fifty50Button))
                .addGap(4, 4, 4)
                .addGroup(gameButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameButtonPanelLayout.createSequentialGroup()
                        .addComponent(bButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dButton))
                    .addGroup(gameButtonPanelLayout.createSequentialGroup()
                        .addComponent(askAudButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        gameButtonPanelLayout.setVerticalGroup(
            gameButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(gameButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aButton)
                    .addComponent(bButton)
                    .addComponent(cButton)
                    .addComponent(dButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gameButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fifty50Button)
                    .addComponent(askAudButton)
                    .addComponent(phoneButton))
                .addGap(41, 41, 41)
                .addGroup(gameButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(quitButton)
                    .addComponent(helpButton))
                .addContainerGap())
        );

        buttonPanel.add(gameButtonPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WWTBAMView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WWTBAMView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WWTBAMView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WWTBAMView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() {
                new WWTBAMView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aButton;
    private javax.swing.JButton askAudButton;
    private javax.swing.JButton bButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cButton;
    private javax.swing.JButton dButton;
    private javax.swing.JButton fifty50Button;
    private javax.swing.JPanel gameButtonPanel;
    private javax.swing.JButton helpButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton phoneButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel textDisplayLabel;
    private javax.swing.JPanel textDisplayPanel;
    // End of variables declaration//GEN-END:variables

    public JButton getAButton() 
    {
        return aButton;
    }

    public JButton getAskAudButton() 
    {
        return askAudButton;
    }

    public JButton getBButton() 
    {
        return bButton;
    }

    public JPanel getButtonPanel() 
    {
        return buttonPanel;
    }

    public JButton getCButton() 
    {
        return cButton;
    }

    public JButton getFifty50Button() 
    {
        return fifty50Button;
    }

    public JPanel getGameButtonPanel() 
    {
        return gameButtonPanel;
    }

    public JButton getHelpButton() 
    {
        return helpButton;
    }

    public JButton getPhoneButton() 
    {
        return phoneButton;
    }

    public JButton getQuitButton() 
    {
        return quitButton;
    }

    public JButton getStartButton() 
    {
        return startButton;
    }

    public JLabel getTextDisplayLabel() 
    {
        return textDisplayLabel;
    }

    public JButton getDButton() 
    {
        return dButton;
    }

    public JTextField getNameTextField() 
    {
        return nameTextField;
    }

    public JPanel getTextDisplayPanel() 
    {
        return textDisplayPanel;
    }
    
    public int showPlayAgain()
    {
        return JOptionPane.showConfirmDialog(null, "Do you want to play again?", "Play again?", YES_NO_OPTION);
        
    }
    
    /**
     * method for enabling and disabling main play buttons
     * @param toggle 
     */
    public void enableButtons(boolean toggle)
    {
        getAskAudButton().setEnabled(toggle);
        getPhoneButton().setEnabled(toggle);
        getFifty50Button().setEnabled(toggle);
        getAButton().setEnabled(toggle);
        getBButton().setEnabled(toggle);
        getCButton().setEnabled(toggle);
        getDButton().setEnabled(toggle);  
    }
}
